"""subject table

Revision ID: b17a11418818
Revises: fb35fd8e0709
Create Date: 2020-03-19 13:53:34.944146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a11418818'
down_revision = 'fb35fd8e0709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('assigned_student', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'student', ['assigned_student'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'assigned_student')
    # ### end Alembic commands ###
